export const PRODUCTS = [
  {
    id: 1,
    name: "BMW M series",
    description: "Description for product 1",
    price: 10.0,
    image: "/images/BMW M series.jpg",
  },
  {
    id: 2,
    name: "Mercedes Benz",
    description: "Description for product 2",
    price: 20.0,
    image: "/images/Mercedes.jpg",
  },
  {
    id: 3,
    name: "Audi",
    description: "Description for product 3",
    price: 20.0,
    image: "/images/AUDI.jpg",
  },
  {
    id: 1,
    name: "BMW M series",
    description: "Description for product 1",
    price: 10.0,
    image: "/images/BMW M series.jpg",
  },
  {
    id: 2,
    name: "Mercedes Benz",
    description: "Description for product 2",
    price: 20.0,
    image: "/images/Mercedes.jpg",
  },
  {
    id: 3,
    name: "Audi",
    description: "Description for product 3",
    price: 20.0,
    image: "/images/AUDI.jpg",
  },
  {
    id: 1,
    name: "BMW M series",
    description: "Description for product 1",
    price: 10.0,
    image: "/images/BMW M series.jpg",
  },
  {
    id: 2,
    name: "Mercedes Benz",
    description: "Description for product 2",
    price: 20.0,
    image: "/images/Mercedes.jpg",
  },
  {
    id: 3,
    name: "Audi",
    description: "Description for product 3",
    price: 20.0,
    image: "/images/AUDI.jpg",
  },
  {
    id: 1,
    name: "BMW M series",
    description: "Description for product 1",
    price: 10.0,
    image: "/images/BMW M series.jpg",
  },
  {
    id: 2,
    name: "Mercedes Benz",
    description: "Description for product 2",
    price: 20.0,
    image: "/images/Mercedes.jpg",
  },
  {
    id: 3,
    name: "Audi",
    description: "Description for product 3",
    price: 20.0,
    image: "/images/AUDI.jpg",
  },
];
